### ISSUE TITLE
undefined symbol: _ZNK3c104Type14isSubtypeOfExtESt10shared_ptrIS0_EPSo

### ISSUE THREAD

**Issue by muammar** [rusty1s/pytorch_cluster#100]
I installed `pytorch_cluster` as a dependency needed by another library, and I am having this issue: 

```
OSError: ~/miniconda3/envs/py38/lib/python3.8/site-packages/torch_cluster/_grid_cuda.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtESt10shared_ptrIS0_EPSo
```

Does anyone know which system library provides the symbol `_ZNK3c104Type14isSubtypeOfExtESt10shared_ptrIS0_EPSo`?

Best,

**Comment by rusty1s** [comment]
This error is injected by PyTorch in case PyTorch or CUDA versions for which the package were compiled do not match with the ones for which the package is executed.

**Comment by muammar** [comment]
> This error is injected by PyTorch in case PyTorch or CUDA versions for which the package were compiled do not match with the ones for which the package is executed.

Thanks for your reply. I will check and download the right version, report back, and close the report!

**Comment by muammar** [comment]
You were right. I had pytorch `1.8.1`. I downgraded to `1.8.0`, and installed `pytorch_cluster` with the pip flag `--no-cache-dir`. The wheel was recompiled, and it worked. I will close this report. Thanks.
