### ISSUE TITLE
Lower radius for radius_graph

### ISSUE THREAD

**Issue by PhilippThoelke** [rusty1s/pytorch_cluster#104]
Hi, for my application I need to collect all neighbors with radius r_lower <= r < r_upper. As the `radius_graph` function works with an upper radius, I was wondering if it would be possible to also specify a lower radius to only get neighbors between the two bounds. 

Currently I'm recomputing the radius after the `radius_graph` call and mask out the entries from `edge_index`, which are below the lower bound. It feels like this is inefficient, even though I need the radius later on anyways.

**Comment by rusty1s** [comment]
This should be quite straightforward to add by just modifying [this](https://github.com/rusty1s/pytorch_cluster/blob/master/csrc/cuda/radius_cuda.cu#L34) condition. Please let me know if you are interested in contributing this feature.

**Comment by PhilippThoelke** [comment]
Yes, I'll have a look into it. The change for the CPU version doesn't seem as straightforward though.

**Comment by rusty1s** [comment]
Yes, that's true. We rely on `nanoflann` here. I'm currently not sure if `nanoflann` allows for such an option.

**Comment by PhilippThoelke** [comment]
Unfortunately it does not seem like `nanoflann` is supporting this feature. I don't think it will be worth looking into it for me then as the performance is not impacted too much in my case. Anyways, thank you!
