### ISSUE TITLE
[BUG] incorrect calculation in radius_graph?

### ISSUE THREAD

**Issue by tueboesen** [rusty1s/pytorch_cluster#106]
I believe there is a bug in radius_graph.
The following code creates a 100 random 3d vectors and rotates them. Then it compares the radius_graph of the vectors before and after rotation, and it finds that there is a difference in these graphs. Note that there doesn't seem to be a problem when n=10 rather than 100
 
```

import torch
from e3nn import o3
from torch_cluster import radius_graph
import numpy as np

torch.set_default_dtype(torch.float64)


def Distogram(r):
    """
    r should be of shape (n,3)
    """
    D = torch.relu(torch.sum(r.t() ** 2, dim=0, keepdim=True) + torch.sum(r.t() ** 2, dim=0, keepdim=True).t() - 2 * r @ r.t())
    return D


n = 100
irreps_in = o3.Irreps("1x1o")
x = irreps_in.randn(n, -1)

rot = o3.rand_matrix()
Dx = irreps_in.D_from_matrix(rot)

max_radius = 2
batch = torch.zeros(n, dtype=torch.int64)

edge_index = radius_graph(x, max_radius, batch)
edge_src = edge_index[0]
edge_dst = edge_index[1]

x_rot = x @ Dx

# Lets just confirm that the inter-distances between points in x and x_rot are the same
d = Distogram(x)
d_rot = Distogram(x_rot)
print("Distograms match={:}".format(torch.allclose(d,d_rot)))


edge_index_rot = radius_graph(x_rot, max_radius, batch)
edge_src_rot = edge_index_rot[0]
edge_dst_rot = edge_index_rot[1]

a = torch.cat([edge_dst[:, None], edge_src[:, None]], dim=1)
a2 = torch.cat([edge_dst_rot[:, None], edge_src_rot[:, None]], dim=1)

an = a.numpy()
a2n = a2.numpy()
ind = np.lexsort((an[:, 1], an[:, 0]))
an_sorted = an[ind]
ind = np.lexsort((a2n[:, 1], a2n[:, 0]))
a2n_sorted = a2n[ind]

M = (an_sorted == a2n_sorted).all()
print("Graphs identical={:}".format(M))
```

**Comment by rusty1s** [comment]
You need to set the `max_num_neighbors` argument to a higher value, see [here](https://github.com/rusty1s/pytorch_cluster/blob/master/torch_cluster/radius.py#L93), which denote the maximum number of neighbors returned for a single node. In case there exists more nodes inside a ball than `max_num_neighbors`, it will randomly pick nodes in case instead.

**Comment by tueboesen** [comment]
It would probably be a good idea to include that the neighbors are picked randomly if there are more than the maximum number, I read the documentaion, but expected it to pick the 32 closest ones.

**Comment by rusty1s** [comment]
You are right. Added the missing piece of information to the documentation.
