### ISSUE TITLE
python version 

### ISSUE THREAD

**Issue by hirokic5** [rusty1s/pytorch_cluster#107]
Hi, thanks for great repository. 
I would use pytorch_cluster, and tried to install from binaries, but I couldn't. 
After several trials, I found that installation succeeded in the case python version <= 3.8 (and failed in python version>= 3.9). 
Is this behavior within your expectations ? 

thank you

**Comment by rusty1s** [comment]
I'm sorry for the confusion. The wheels are indeed only provided for Python<=3.8 which is only mentioned in the PyG documentation (https://github.com/rusty1s/pytorch_geometric#pytorch-180181). I will provide Python 3.9 wheels in the next release cycle.

**Comment by hirokic5** [comment]
Thank you for your quick and polite response ! I understood it.
