### ISSUE TITLE
How to get grid centers from grid_cluster?

### ISSUE THREAD

**Issue by SamGalanakis** [rusty1s/pytorch_cluster#108]
Hi,

I am using grid_cluster to voxelize a point cloud but also need the voxel centers, is there a way to calculate them from the grid size and the voxel index?

Thanks in advance.

**Comment by rusty1s** [comment]
This is untested, but you should be able to get the center coordinates (in 2D) via:
```python
start = pos.min(dim=0)[0]
end = pos.max(dim=0)[0]
num_voxels = ((end - start) / size).long() + 1

x_center = torch.arange(start[0] + size[0] / 2, end[0] + size[0] / 2, size[0])
y_center = torch.arange(start[1] + size[1] / 2, end[1] + size[1] / 2, size[1])

x_center = x_center.view(1, -1).repeat(num_voxels[1], 1)
y_center = y_center.view(-1, 1).repeat(1, num_voxels[0])

center = torch.stack([x_center, y_center], dim=-1).view(-1, 2)
```

**Comment by SamGalanakis** [comment]
Thanks, adapted it to n dimensions:

`def get_all_voxel_centers(start,end,size):
    n_dims = len(size)
    axis_centers = [torch.arange(start[i] + size[i] / 2, end[i] + size[i] / 2, size[i]) for i in range(n_dims)]
    centers = torch.stack(torch.meshgrid(*axis_centers[::-1])).reshape((n_dims,-1)).T.flip(-1)
    return centers `

I tested it in 3 dimensions but should work generally if someone else finds it useful. The odd reshapes are to get the indexing to match, there is probably a more direct way of doing that.
