### ISSUE TITLE
Error importing CPU wheel on machine with CUDA

### ISSUE THREAD

**Issue by aphedges** [rusty1s/pytorch_cluster#113]
Looking at [`__init__.py`](https://github.com/rusty1s/pytorch_cluster/blob/4ad2b395b25ee0fdad917fc27bab2481808f3672/torch_cluster/__init__.py), it seems that this package as the same issue as <https://github.com/rusty1s/pytorch_scatter/issues/229>. The fixed used in <https://github.com/rusty1s/pytorch_scatter/commit/778f62459ab33497ae13ccbd2d3bb63d7f038020> probably would work here as well.

**Comment by rusty1s** [comment]
Fixed in https://github.com/rusty1s/pytorch_spline_conv/commit/10bfaf3609c5003ca2b3ecd12e96ec2d54ccd637
