### ISSUE TITLE
knn need check or conversion of x dtype

### ISSUE THREAD

**Issue by cutecutecat** [rusty1s/pytorch_cluster#117]
In `knn.py`, `torch.ops.torch_cluster.knn` may call `Half` inside?

https://github.com/rusty1s/pytorch_cluster/blob/0d735d7eb34476c491fb952a32f979a64aa8337c/torch_cluster/knn.py#L70

If `x` type is `torch.float16`, `Half` will lead to a `RuntimeError: value cannot be converted to type at::Half without overflow: 1e+38`, even `x` is not beyond `1e+38`. This may need much chaos, makes it harder to debug.

If `x` type is `torch.float32`, everything is ok.

From where I stand, here might need a check of whether x is `torch.float16`, and a exception or auto conversion could be taken into consideration.

**Comment by cutecutecat** [comment]
Sorry, it's my fault of using `torch.amp.autocast()` caused this.

**Comment by rusty1s** [comment]
Let me re-open this, and try to integrate half-precision support into `torch-cluster` :)

**Comment by rusty1s** [comment]
I added half-precision support to `torch-cluster`, see https://github.com/rusty1s/pytorch_cluster/pull/119. I will craft a new official release soon, meanwhile you have to install from source for this feature :)

**Comment by cutecutecat** [comment]
Wow! So cool!
