### ISSUE TITLE
Sample at least k points in fps

### ISSUE THREAD

**Issue by HankerWu** [rusty1s/pytorch_cluster#118]
Hi, there.
Thanks for providing the methods of farthest point sampling.

Is there any plan to add a parameter `k` to the function `torch_cluster.fps`, that is, the minimum number of points obtained by sampling? I know that the parameter `ratio` can control the number of output points, but it controls the entire batch, and the number of points in a batch is usually different. I want to downsample the batch with a ratio `r` and keep the number of points in the batch greater than `k`. 

Thank you in advance!

**Comment by rusty1s** [comment]
This was just recently added to `torch_cluster.fps`, see [here](https://github.com/rusty1s/pytorch_cluster/blob/master/torch_cluster/fps.py#L19-L36), and should be available when installing from source.

That is, `ratio` can now be a `torch.Tensor`, with different sampling ratios for each example. You should be able to adjust the sampling ratios per example to fit your specific needs.

**Comment by HankerWu** [comment]
Thank you~ @rusty1s
