### ISSUE TITLE
The meaning of P in paramter

### ISSUE THREAD

**Issue by Tianqi-py** [rusty1s/pytorch_cluster#122]
Hi, 

thanks for implementing such a helpful package:)

I have a question about the meaning of P in the parameter. It says "Likelihood of immediately revisiting a node in the walk. " Does this mean a random node in the previously visited nodes?

For example: walk: a->b->c->d->
Now if we set p=0.2, it will revisit a or b or c with the probability of 0.2?

Thanks!

**Comment by rusty1s** [comment]
It's best to look at Figure 2 in the [node2vec](https://arxiv.org/pdf/1607.00653.pdf) paper to understand this.

If you set `p=0.2`, the random walk has a `1/0.2 = 5` times higher chance to immediately revisit the original node.
