### ISSUE TITLE
batchwise fps and knn

### ISSUE THREAD

**Issue by ananyajana** [rusty1s/pytorch_cluster#124]
Hi ,
thank you for sharing the library.
I have used it and it's really good and very fast.

could you please share how we can use the fps and knn function in a batchwise manner?
I would like to use the functions fps and knn in a pytoch neural network model.

This is the scenario:
input torch.Size([8, 200, 24])
where 
8: batch size
200: number of points
24: number of features per point

I would like to calculate the knn of this function fo r4 nearest neighbors such that the output is
torch.Size([8, 2, 800]).
Also I would like to  use fps similarly in batchwise fashion.
could you please help?

thanks,
Ananya

**Comment by rusty1s** [comment]
Seems like I missed this issue, really sorry. Batch-wise computation is done through the `batch` vectors, which assigns each point to a single example.
