### ISSUE TITLE
Non-intuitive behavior of `radius_graph` when `max_num_neighbors` is too small.

### ISSUE THREAD

**Issue by raimis** [rusty1s/pytorch_cluster#128]
Let's create 3 points in 1D space:
```python
import torch as pt
from torch_cluster import radius_graph

x = pt.tensor([[0.], [1.], [2.]], device='cuda')
```

If `max_num_neighbors` is 2 or more, it find the expected number of neighbors (6 = 3 points x 2 neighbors):
```python
radius_graph(x, r=2.5, max_num_neighbors=2)
tensor([[1, 2, 0, 2, 0, 1],
        [0, 0, 1, 1, 2, 2]], device='cuda:0')
```

If `max_num_neighbors` is 1 (too small), it finds just 4 neighbors (it should be 3 = 3 points x 1 neighbor) and misses the rest:
```python
radius_graph(x, r=2.5, max_num_neighbors=1)
tensor([[1, 0, 0, 1],
        [0, 1, 2, 2]], device='cuda:0')
```

I cannot image any application, where it could be a desired behavior. So, the function should fail if `max_num_neighbors` is too small.

**Comment by raimis** [comment]
This is not resolved!

**Comment by rusty1s** [comment]
Yes, indeed. For now, this is fixable by setting `radius(loop=True)`. There is currently some inconsistency when setting `max_num_neighbors` to a low value since the self-loop might be sampled or not.
