### ISSUE TITLE
CUDA 11.6 Support

### ISSUE THREAD

**Issue by nicovandenhooff** [rusty1s/pytorch_cluster#129]
Hi there - firstly thanks for creating `torch_geometric` and also `torch_cluster`.

I'm currently having some trouble installing `torch_cluster` since I'm working with cuda 11.6 but I believe the most recent cuda version supported by `torch_cluster` is 11.5.

We've tried installing `torch_cluster` with cuda 11.5 support since it's the most recent but unfortunately when running `import torch_cluster` we receive an `OSError` (caused by the cuda version, error pasted at the bottom of this issue).

My question would be - would it be possible to provide a `torch_cluster` package version that supports cuda 11.6 (or maybe this is already in the works)?

Thank you for your help.

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Input In [1], in <module>
----> 1 import torch_cluster

File /opt/conda/lib/python3.8/site-packages/torch_cluster/__init__.py:18, in <module>
     16 spec = cuda_spec or cpu_spec
     17 if spec is not None:
---> 18     torch.ops.load_library(spec.origin)
     19 else:  # pragma: no cover
     20     raise ImportError(f"Could not find module '{library}_cpu' in "
     21                       f"{osp.dirname(__file__)}")

File /opt/conda/lib/python3.8/site-packages/torch/_ops.py:219, in _Ops.load_library(self, path)
    214 path = torch._utils_internal.resolve_library_path(path)
    215 with dl_open_guard():
    216     # Import the shared library into the process, thus running its
    217     # static (global) initialization code in order to register custom
    218     # operators with the JIT.
--> 219     ctypes.CDLL(path)
    220 self.loaded_libraries.add(path)

File /opt/conda/lib/python3.8/ctypes/__init__.py:373, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    370 self._FuncPtr = _FuncPtr
    372 if handle is None:
--> 373     self._handle = _dlopen(self._name, mode)
    374 else:
    375     self._handle = handle

OSError: /opt/conda/lib/python3.8/site-packages/torch_cluster/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
```

**Comment by rusty1s** [comment]
It looks like installation has succeeded, but there is a version mismatch between the CUDA version of PyTorch and the CUDA version you are using to install `torch-cluster`. Can you confirm?
```python
import torch
print(torch.version.cuda)
```
In general, these have to match.

**Comment by rusty1s** [comment]
Yes, I think so :( Will work on providing CUDA 11.6 support once a new PyTorch release officially supports it.

**Comment by nicovandenhooff** [comment]
OK thanks @rusty1s, appreciate your help!
