### ISSUE TITLE
Get edge attributes for random walk 

### ISSUE THREAD

**Issue by jacobdanovitch** [rusty1s/pytorch_cluster#137]
Hi,

I'm trying to get the edge attributes for each step in a random walk, with the use case of trying to retain edge types in a walk on a heterogeneous graph I've converted to homogeneous. Using the idea in rusty1s/pytorch_sparse#214, I have this so far:

```python
import torch
from torch_geometric.datasets import DBLP
from torch_cluster import random_walk

def get_edge_attr(edge_index: torch.Tensor, edge_attr: torch.Tensor, query_row: torch.Tensor, query_col: torch.Tensor) -> torch.Tensor:
    row, col = edge_index
    row_mask = row == query_row.view(-1, 1)
    col_mask = col == query_col.view(-1, 1)
    mask = torch.max(torch.logical_and(row_mask, col_mask), dim=0).values
    return edge_attr[mask]

data = DBLP()[0].to_homogeneous()

num_walks = 1
walk_length = 5

start = torch.arange(data.num_nodes).view(-1, 1).repeat(1, num_walks).view(-1)
rw = random_walk(data.edge_index[0], data.edge_index[1], start, walk_length, num_nodes=data.num_nodes)
print(rw)
>>> tensor([[    0, 10514, 19555, 10973, 21385,  9952],
...        [    1,  6520, 20381,  6520, 20381,  6520]])

l, r = rw[:2].unfold(1, 2, 1).flatten().t() # sliding window of size 2 over each walk
print(get_edge_attr(data.edge_index, data.edge_type, l, r))
>>> tensor([1, 1, 4, 4, 4, 2, 2, 2])
```

I know this can be made more efficient with `searchsorted` as mentioned in the linked issue, but is this correct in general? Is there a built-in way to do this that I've missed or is this my best bet? 

Thanks in advance.

**Comment by rusty1s** [comment]
I think this would be way easier if we would just return the edge indices in `random_walk` :(
I guess your approach works, but will be indeed inefficient.

**Comment by jacobdanovitch** [comment]
> I think this would be way easier if we would just return the edge indices in `random_walk` :( I guess your approach works, but will be indeed inefficient.

Yeah, I'm certainly not a huge fan of this approach. It struggles with DBLP on a laptop (not an overpowered one, but pretty solid). For now I'm doing this awfulness: 

```python
et = data.adj_t.to_scipy('csc')
l, r = rw.unfold(-1, 2, 1).flatten(0, 1).t().cpu().numpy()
walk_etypes = torch.from_numpy(et[l.tolist(), r.tolist()]).to(rw.device).view(-1, walk_length)
```

Obviously not ideal compared to returning to edge indices. How difficult would that be to implement?

**Comment by rusty1s** [comment]
If you are interested, we can add support for this in [`pyg-lib`](https://pyg-lib.readthedocs.io/en/latest/modules/sampler.html#pyg_lib.sampler.random_walk), which should be straightforward to add. It also supports nightly builds so it should be ready to use once it lands. Let me know if you have interest in contributing!

**Comment by jacobdanovitch** [comment]
> If you are interested, we can add support for this in [`pyg-lib`](https://pyg-lib.readthedocs.io/en/latest/modules/sampler.html#pyg_lib.sampler.random_walk), which should be straightforward to add. It also supports nightly builds so it should be ready to use once it lands. Let me know if you have interest in contributing!

Absolutely. Only issue is I haven't written C++ in several years and I've never written anything Torch or CUDA related with it. I can kind of follow along the [CPU](https://github.com/pyg-team/pyg-lib/blob/master/pyg_lib/csrc/sampler/cpu/random_walk_kernel.cpp) implementation but the [CUDA](https://github.com/pyg-team/pyg-lib/blob/master/pyg_lib/csrc/sampler/cuda/random_walk_kernel.cu) one looks like it would take me a while to understand. I can do the grunt work but I'd probably need help understanding how it works and what would need to be changed.

**Comment by pbielak** [comment]
Hey, I am also looking for such a feature (i.e., using edge indices from a random walk), and I did a quick update to the `random_walk` function. The edge indices are computed by the underlying C++/CUDA implementations, so we just need to return them.

**Comment by rusty1s** [comment]
Reference: #139 
Thanks @pbielak!

**Comment by jacobdanovitch** [comment]
> @jacobdanovitch Your example code will now simplify as follows:

Works perfectly, thanks so much @pbielak!
