### ISSUE TITLE
setup.py doesnt specify torch as dependency leading to downstream failures

### ISSUE THREAD

**Issue by KukumavMozolo** [rusty1s/pytorch_cluster#138]
Hi there, 

is there any chance that you will add torch as a requirement to setup.py or adopt [PEP 517](https://peps.python.org/pep-0517/)?
I am running into problems installing this package while trying to install it using pip-tools as I described here:
https://github.com/jazzband/pip-tools/issues/1662#issuecomment-1202839911

**Comment by KukumavMozolo** [comment]
Thank you for your reply,
I am not really knowledgeable on that matter but this [https://github.com/huggingface/transformers](https://github.com/huggingface/transformers) project also depends on torch and I do not recall running into similar problems installing it via pip-tools.
Maybe there is a solution there?

**Comment by rusty1s** [comment]
Well, that‘s because transformers is Python only - it does not need to compile CUDA kernels.
