### ISSUE TITLE
Incompatibility with bfloat16

### ISSUE THREAD

**Issue by PabloVD** [rusty1s/pytorch_cluster#145]
Hi,

I tried to run `torch_cluster.radius_graph` in CUDA with bfloat16 data and I got the following error:

```
    return torch.ops.torch_cluster.radius(x, y, ptr_x, ptr_y, r,
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                                          max_num_neighbors, num_workers)
RuntimeError: "_" not implemented for 'BFloat16'
```

Is torch_cluster compatible with `torch.bfloat16` format?

Thanks in advance.

**Comment by rusty1s** [comment]
We just recently added support for this. You sadly need to install from master for now to get `torch.bfloat16` support.

**Comment by PabloVD** [comment]
Great, thanks for the response!
