### ISSUE TITLE
radius_graph and knn_graph with zero size tensor leads to segmentation fault

### ISSUE THREAD

**Issue by maabuu** [rusty1s/pytorch_cluster#156]
The following corner case leads to a segmentation fault.

```
import torch
from torch_cluster import radius_graph

x = torch.rand(0, 3)
radius_graph(x, r=5.0)
```

The same is true for `knn_graph` instead of `radius_graph`. 

I am on linux and used conda to install python 3.10.8, pytorch 1.13.0 and pytorch_cluster 1.6.0.

**Comment by rusty1s** [comment]
Thanks for reporting. I fixed this via https://github.com/rusty1s/pytorch_cluster/commit/3316bdc787f1f7ee78ab727fd065fc34b4123cd2.
