### ISSUE TITLE
Error Compiling with Python 2.0 

### ISSUE THREAD

**Issue by CoryKornowicz** [rusty1s/pytorch_cluster#159]
I know this issue has been mentioned in pytorch_scatter's issues, but there was never an error log posted. Here is the error I am receiving, 
[output_err_torch_cluster.log](https://github.com/rusty1s/pytorch_cluster/files/10475141/output_err_torch_cluster.log)

I am running on an M1 system, so I recompile all of the accessory packages for pytorch_geometric upon installation, "pip install git+https...". On the other hand, I have compiled torch_scatter successfully for Pytorch 2.0 using this pip install method, and this is the only package so far not compiling -- maybe this issue is a quick fix after all.

**Comment by rusty1s** [comment]
This should be fixed once https://github.com/rusty1s/pytorch_cluster/pull/160 is merged, thanks for letting me know :)
