### ISSUE TITLE
Question: Can any coordinate reference system be used?

### ISSUE THREAD

**Issue by Anjum48** [rusty1s/pytorch_cluster#162]
Apologies for the slightly silly question but I couldn't find anything immediately obvious in the docs.

For the `knn_graph` and `radius` functions do the features need to be cartesian or can any CRS be used (e.g. cylindrical, spherical, etc.)?

**Comment by rusty1s** [comment]
Currently, we only support Cartesian.

**Comment by Anjum48** [comment]
Ok thanks for the speedy response!
