### ISSUE TITLE
INTERNAL ASSERT FAILED for knn for k > 100

### ISSUE THREAD

**Issue by lodurality** [rusty1s/pytorch_cluster#164]
Hi, I have the following issue with torch_cluster knn:

```
File "/home/dmpetrov/Repos/shape_generation/models/skelnet.py", line 85, in forward
    row, col = knn(pos_skel, pos_skel[idx], self.num_skel_nn, batch2, batch1[idx])
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/dmpetrov/anaconda3/lib/python3.8/site-packages/torch_cluster/knn.py", line 70, in knn
        ptr_y = torch.bucketize(arange, batch_y)

    return torch.ops.torch_cluster.knn(x, y, ptr_x, ptr_y, k, cosine,
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                                       num_workers)
RuntimeError: k <= 100 INTERNAL ASSERT FAILED at "csrc/cuda/knn_cuda.cu":98, please report a bug to PyTorch. `k` needs to smaller than or equal to 100
```

Shapes of inputs are 
`torch.Size([2048, 3]) torch.Size([512, 3])
`
I have tested the bug and it indeed only persists if k > 100 (as message says). Here is code that reproduces it:

```
from torch_cluster import knn

input1 = torch.randn(2048,3).to('cuda')
input2 = torch.randn(512,3).to('cuda')
knn(input1, input2,101)

```
Pytorch version is 1.12.0+cu102. 
torch_cluster version is 1.6.0.

Is there a way to bypass this issue? Should I use different version of cuda/pytorch/torch_cluster? If yes, what combination will work?

Thank you for your help!

**Comment by lodurality** [comment]
I have also tested this issue in Google Colab and it persists as well.

torch_cluster/pytorch/cuda version there is 1.6.0+pt113cu116

**Comment by lodurality** [comment]
Is it safe to remove this assert to bypass this issue?

**Comment by rusty1s** [comment]
This would require changes here: https://github.com/rusty1s/pytorch_cluster/blob/master/csrc/cuda/knn_cuda.cu#L44. What `k` do you want to support? Increasing this will result in higher memory requirements when using smaller `k`. Ideally, we template this so that we can support dynamic `k`. Is that something you are interested to add?

**Comment by lodurality** [comment]
Thank you for the fast reply!

Initially, I wanted it to run with k=128. Right now, I am running it with 100. I am okay with higher memory consumption since it is still more efficient then doing it naive way (computing all distances and argsorting them). 

> Is that something you are interested to add?

Do you want me to submit a pull request or just looking for input?

I think that it might make sense to replace assert with warning and let user decide whether they want this trade-off.

**Comment by rusty1s** [comment]
Yeah, I was looking for active contribution, otherwise I try to find some time to implement it by myself.

I was imaging all we need to do is to add some additional template arg
``` 
template <typename scalar_t, int max_k>
__global__ void
knn_kernel(...) {
    ...
  scalar_t best_dist[max_k];
  int64_t best_idx[max_k];
```
and then call it [here](https://github.com/rusty1s/pytorch_cluster/blob/master/csrc/cuda/knn_cuda.cu#L126) with different `k`, e.g.:
if (k < 32)
    knn_kernel<scalar_t, 32>(...)
if (k < 64)
    knn_kernel<scalar_t, 64>(...)
if (k < 128)
    knn_kernel<scalar_t, 128>(...)
```
and so on.

**Comment by lodurality** [comment]
I would be happy to contribute but I am not familiar with CUDA programming, so it might take some time for me to figure things out (but it looks simple enough).

I will try to do it by the end of the week.

**Comment by rusty1s** [comment]
Thank you! Happy to help the best I can. Just ping me :)
