### ISSUE TITLE
How to sample k points in fps

### ISSUE THREAD

**Issue by 1170801121** [rusty1s/pytorch_cluster#174]
Hi,

I want to use fps to sample 100 points every time from N points. N can vary from time to time. And I use 100/N as the ratio parameter of fps function. But sometimes, it will give me 101 points (e.g., when N=732). So, how can I exactly get 100 points every time? I think maybe it is helpful if you could add a parameter k to represent the number of sampled points, rather than the ratio.

Thank you for the help!

**Comment by rusty1s** [comment]
I am sorry we currently only provide ratio rather than absolute thresholds. In the end, you could simply slice your data to 100 points since they will be ordered by the order of sampling.

**Comment by 1170801121** [comment]
Many thanks for the advice!

**Comment by 1170801121** [comment]
One more question, will the sampled index be duplicated? Because I saw some codes use fps as follows:
fps_index = fps(feat, None, ratio=ratio, random_start=False).unique()
I am wondering whether the unique() function is necessary here?

**Comment by rusty1s** [comment]
No, it is not.
