### ISSUE TITLE
Pytorch 2.0.1-cu117 Package installation is not working

### ISSUE THREAD

**Issue by IoSonoMarco** [rusty1s/pytorch_cluster#177]
I always obtain ERROR: Could not build wheels for torch-cluster, with both conda and pip installations of torch-cluster

**Comment by rusty1s** [comment]
Can you share more information? What is the output of `pip install --verbose torch-cluster -f and so on`?

**Comment by IoSonoMarco** [comment]
This is the final output I can see at the very very end

Building wheel for torch-cluster (setup.py) ... error
  ERROR: Failed building wheel for torch-cluster
  Running setup.py clean for torch-cluster
  Running command python setup.py clean
  running clean
  removing 'build\temp.win-amd64-cpython-39' (and everything under it)
  removing 'build\lib.win-amd64-cpython-39' (and everything under it)
  'build\bdist.win-amd64' does not exist -- can't clean it
  'build\scripts-3.9' does not exist -- can't clean it
  removing 'build'
  Error in atexit._run_exitfuncs:
  Traceback (most recent call last):
    File "C:\Users\marco\anaconda3\envs\DL\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
      return stream.closed
  ValueError: underlying buffer has been detached
Failed to build torch-cluster
ERROR: Could not build wheels for torch-cluster, which is required to install pyproject.toml-based projects

**Comment by rusty1s** [comment]
Looks like this compiles from source? Can you show me the exact command you use to install? What happens if you run
```
pip install --verbose --no-index torch-cluster -f https://data.pyg.org/whl/torch-2.0.0+cu117.html

**Comment by IoSonoMarco** [comment]
Oh well, this seems to have fixed the issue! Thaaaaanks
