### ISSUE TITLE
knn does not work with cuda even if it works with cpu data.

### ISSUE THREAD

**Issue by lch32111** [rusty1s/pytorch_cluster#181]
![image](https://github.com/rusty1s/pytorch_cluster/assets/19434311/d7f8f4d9-c7b1-4fa3-9cb4-28b9d5137db0)

Hello! I'm using pytorch_cluster now. Its knn works with cpu data, but it does not work with cuda data. Can I get any solution for this problem?

**Comment by rusty1s** [comment]
Mh, that works for me. How did you install `torch_cluster`? And what is the output of `nvidia-smi` for you?

**Comment by lch32111** [comment]
This is the output of `nvidia-smi`
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 461.92       Driver Version: 461.92       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070   WDDM  | 00000000:21:00.0 Off |                  N/A |
| 33%   34C    P2    31W / 175W |   2136MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

I downloaded torch-cluster by pip.
I guess my CUDA Version can be a problem for this?

**Comment by rusty1s** [comment]
Does closed mean you solved it?

**Comment by lch32111** [comment]
> Does closed mean you solved it?

Yeap. Because it works now. Do you have more things to do?

**Comment by rusty1s** [comment]
No, all good. Just saw you edited the message :)
