### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by tueboesen** [rusty1s/pytorch_cluster#182]
On https://pypi.org/project/torch-cluster/ I notice that it says 
`pip install torch-spline-conv -f https://data.pyg.org/whl/torch-2.0.0+${CUDA}.html`
I believe this has been copy pasted from torch-spline and should be torch cluster or something similar.

**Comment by rusty1s** [comment]
Yes :( This is already fixed in master and should be resolved once we upgrade the version.
