### ISSUE TITLE
Support Python 3.11 for conda packages

### ISSUE THREAD

**Issue by function2-llx** [rusty1s/pytorch_cluster#187]
Dear developers, 
It will be great if there are pre-built conda packages available for Python 3.11. Currently, they're available for Python 3.7-3.10 ([files](https://anaconda.org/pyg/pytorch-cluster/files)). Thanks a lot!
Best regards

**Comment by rusty1s** [comment]
We will likely provide this when PyTorch 2.1 arrives. Hope that works for you.

**Comment by function2-llx** [comment]
Great to hear that, thanks!

**Comment by function2-llx** [comment]
Okay, I think there's already the same issue in the pyg repository (https://github.com/pyg-team/pytorch_geometric/issues/6704).
