### ISSUE TITLE
CUDA 12.1 binaries

### ISSUE THREAD

**Issue by schmidt-ai** [rusty1s/pytorch_cluster#190]
The recently-released pytorch 2.1 ships binaries compiled with CUDA 12.1. It would be good to have torch-cluster also have CUDA 12.1 binaries.

**Comment by rusty1s** [comment]
Thanks for the issue. I am working on shipping binaries for PyTorch 2.1. Should be available soon (like 1-2 days).

**Comment by rusty1s** [comment]
Binaries are ready :)
