### ISSUE TITLE
How to run fps algorithm in editable mode?

### ISSUE THREAD

**Issue by utkarsh0902311047** [rusty1s/pytorch_cluster#196]
Hi,
I want to run the fps algorithm in editable mode to understand its working with batch and print out the various variable's values.
How can I do that?
Also is there any Python version of it instead of C++.

**Comment by rusty1s** [comment]
What you can do is install the package in editable mode and debug Python inputs/outputs. If you wanna debug C++ code, there is currently no way besides doing print debugging, and running `python setup.py develop` again.
