### ISSUE TITLE
How to install pytorch_cluster in a win10 based system

### ISSUE THREAD

**Issue by agl71** [rusty1s/pytorch_cluster#198]
hello 
I installed pytorch_cluster in a win10 based systemby using  'pip install torch-cluster', but error occured:
      2 errors detected in the compilation of "csrc/cuda/fps_cuda.cu".
      fps_cuda.cu
      error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.5\\bin\\nvcc.exe' failed with exit status 1
      
The pytorch version is 1.10.0+cu113 ,and i have set the cuda/incluse and cuda/bin in cpath and path respectively.

Best Regards;

**Comment by rusty1s** [comment]
Can you show me the full installation log?
