### ISSUE TITLE
No module named 'torch_cluster.graclus_cuda'

### ISSUE THREAD

**Issue by josauder** [rusty1s/pytorch_cluster#20]
I Install the library using `pip3 install torch-cluster`.

When using the library using `from torch_cluster import knn_graph` I get:

```
Traceback (most recent call last):
  File "/home/jonathan/workspace/pcnn/models/Hybrid.py", line 9, in <module>
    from torch_cluster import knn_graph
  File "/home/jonathan/.local/lib/python3.6/site-packages/torch_cluster/__init__.py", line 1, in <module>
    from .graclus import graclus_cluster
  File "/home/jonathan/.local/lib/python3.6/site-packages/torch_cluster/graclus.py", line 5, in <module>
    import torch_cluster.graclus_cuda
ModuleNotFoundError: No module named 'torch_cluster.graclus_cuda'
```

How can I fix this?
Thanks in advance.

**Comment by rusty1s** [comment]
Your CUDA is not setup correctly. Please follow the installation guide.

**Comment by divyanshj16** [comment]
@josauder were you able to solve this issue?
Pytorch works perfectly with cudatoolkit installed by Anaconda, but this import fails.

**Comment by rusty1s** [comment]
You need to manually install CUDA to make this package work.

**Comment by divyanshj16** [comment]
Oh, Alright. Thanks.

**Comment by gortali** [comment]
I have the same problem, have you managed to solve the issue? my CUDA installation seems fine

**Comment by divyanshj16** [comment]
Reinstall all the libraries again and build them again.
`pip install --no-binary torch-cluster torch-cluster --no-cache-dir`
Do this for all libraries, replacing the name of the library at the appropriate place.
