### ISSUE TITLE
setup.py depends on `torch`

### ISSUE THREAD

**Issue by dyollb** [rusty1s/pytorch_cluster#204]
I would like to create a python package that installs its dependencies properly using `pip`.
Unfortunately, the install fails because pytorch-cluster expects `torch` to already be installed.

Simply trying to install torch-cluster using `pip install torch-cluster` fails. First, you need to install pytorch, and only then install pytorch-cluster.

![image](https://github.com/rusty1s/pytorch_cluster/assets/12702862/83f457e3-3353-43b2-bf83-07fba08ab91d)

Originally I hoped it would simply suffice to add `torch` [here](https://github.com/rusty1s/pytorch_cluster/blob/master/setup.py#L109). But the setup.py depends on torch to build. It seems that [pytorch C++ extensions are done in this way](https://pytorch.org/tutorials/advanced/cpp_extension.html).

Is there any workaround (using `pip`)?

**Comment by rusty1s** [comment]
The only workaround for this right now is to install from the wheels page (i.e., by specifying `-f` in the `pip install` command). This way, `torch` is not required to install the package.

**Comment by dyollb** [comment]
hmm. I did that but it doesn't work. I tried installing (copy pasted from the README) via

```sh
pip install torch-cluster -f https://data.pyg.org/whl/torch-2.1.0+cpu.html
```
which gives me:
![image](https://github.com/rusty1s/pytorch_cluster/assets/12702862/9c0ca489-7923-486e-98d4-799812f62825)

System specs:
- Python 3.10.11
- Apple M2
- Sonoma 14.0
- Darwin Kernel Version 23.0.0

Btw, independent of the issue above, surely `torch-cluster` should explicitly depend on `torch`. Currently it doesn't (see [here](https://github.com/rusty1s/pytorch_cluster/blob/master/setup.py#L109)):
![image](https://github.com/rusty1s/pytorch_cluster/assets/12702862/cc5eafd7-b58d-4cfe-ae50-4beb08722cd0)

**Comment by rusty1s** [comment]
That's because you are trying to install on Apple M2 for which do not exist pre-built wheels (only for Intel-Mac at the moment) :(

**Comment by dyollb** [comment]
Okay, understood. Thanks!
