### ISSUE TITLE
Err: source code compile

### ISSUE THREAD

**Issue by chenbq18** [rusty1s/pytorch_cluster#215]
In conda ven, `python setup.py install`
but have sub err apper!!

> /lib/python3.12/site-packages/torch/include/torch/csrc/jit/api/module.h:409:113: error: use of deleted function ‘torch::jit::Module::Module(torch::jit::Module&&)’
  409 |       bool return_module) // if true include root itself as the first thing
      |                                                                                                                 ^
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/torch/csrc/jit/api/module.h:93:1: note: declared here
   93 |   Module(Module&&) noexcept = default;
      | ^ ~~~~
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h: At global scope:
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h:141:1: warning: attribute ignored [-Wattributes]
  141 |   STRONG_NODISCARD
      | ^
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h:141:1: note: an attribute that appertains to a type-specifier is ignored
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h:143:1: warning: attribute ignored [-Wattributes]
  143 |   STRONG_NODISCARD
      | ^
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h:143:1: note: an attribute that appertains to a type-specifier is ignored
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h:145:1: warning: attribute ignored [-Wattributes]
  145 |   STRONG_NODISCARD
      | ^
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h:145:1: note: an attribute that appertains to a type-specifier is ignored
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h:222:1: warning: attribute ignored [-Wattributes]
  222 |   STRONG_NODISCARD
      | ^
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h:222:1: note: an attribute that appertains to a type-specifier is ignored
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h:235:1: warning: attribute ignored [-Wattributes]
  235 |   STRONG_NODISCARD
      | ^
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h:235:1: note: an attribute that appertains to a type-specifier is ignored
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h:258:1: warning: attribute ignored [-Wattributes]
  258 |     STRONG_NODISCARD
      | ^
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h:258:1: note: an attribute that appertains to a type-specifier is ignored
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h:267:1: warning: attribute ignored [-Wattributes]
  267 |     STRONG_NODISCARD
      | ^
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h:267:1: note: an attribute that appertains to a type-specifier is ignored
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h:276:1: warning: attribute ignored [-Wattributes]
  276 |     STRONG_NODISCARD
      | ^
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h:276:1: note: an attribute that appertains to a type-specifier is ignored
/pubhome/bqchen02/app/mambaforge/envs/torch/lib/python3.12/site-packages/torch/include/c10/util/strong_type.h:285:1: warning: attribute ignored [-Wattributes]
  285 |     STRONG_NODISCARD

**Comment by rusty1s** [comment]
Can you share a bit more information about your system (OS, Python PyTorch version)?

**Comment by chenbq18** [comment]
Thank you reply!
I try install in super-computer. The linux kernel is 4.18.0-425.19.2.el8_7.x86_64!

**Comment by rusty1s** [comment]
And your PyTorch version?
