### ISSUE TITLE
Build fails with latest PyTorch nightly - THRandom has been removed

### ISSUE THREAD

**Issue by Dawars** [rusty1s/pytorch_cluster#22]
Build fails with the latest PyTorch nightly, saying:
```
cpu/sampler.cpp:1:10: fatal error: TH/THRandom.h: No such file or directory

     #include <TH/THRandom.h>

              ^~~~~~~~~~~~~~~
```
**THRandom** was removed in: https://github.com/pytorch/pytorch/pull/21364/files#diff-f5b62748ce692072a882105cff893616L14

**Comment by rusty1s** [comment]
Thank you for the PR!
