### ISSUE TITLE
Support for Python 3.12.*

### ISSUE THREAD

**Issue by Les1ie** [rusty1s/pytorch_cluster#220]
Please support for `Python 3.12.*`.

**Comment by Les1ie** [comment]
`pyg`, `pytorch_scatte`, `pytorch_sparse`, `pytorch_cluster`, and `pytorch-spline-conv` suffer the same problem that they can not be installed via `Conda` in the environment of `Python 3.12`.

**Comment by rusty1s** [comment]
Python 3.12 should be supported. Both pip wheels and conda packages (for Linux) exists. Which error are you seeing?

**Comment by Les1ie** [comment]
Thank you for your response, I found it was my mistake: I installed it with the conda-forge channel by default, not the pyg channel.
