### ISSUE TITLE
undefined symbol: _ZN3c106Device8validateEv

### ISSUE THREAD

**Issue by Xiaoshunxin** [rusty1s/pytorch_cluster#25]
Hi!
I want to install the lastest version of pyg.
After I installed the pytorch-cluster module, I want to verify whether it's correct to install.
But, I have got a error which was shown as follow:

`
ImportError while importing test module '/home/amax/Downloads/0621/pytorch_cluster-master/test/test_sampler.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_sampler.py:3: in <module>
    from torch_cluster import neighbor_sampler
torch_cluster/__init__.py:1: in <module>
    from .graclus import graclus_cluster
torch_cluster/graclus.py:2: in <module>
    import torch_cluster.graclus_cpu
E   ImportError: /home/amax/Downloads/0621/pytorch_cluster-master/torch_cluster/graclus_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c106Device8validateEv
`

I have tried to solve this problem, but I failed!
Can you help me to deal with it?

**Comment by rusty1s** [comment]
Have you followed [installation guide and the FAQ](https://rusty1s.github.io/pytorch_geometric/build/html/notes/installation.html)? It might help if you report your OS/PyTorch version. I have seen this error a lot, and it mostly stems from a mismatch of GCC versions.

**Comment by Xiaoshunxin** [comment]
OS: Linux version 4.15.0-47-generic (buildd@lgw01-amd64-028) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #50~16.04.1-Ubuntu SMP Fri Mar 15 16:06:21 UTC 2019
PyTorch: 1.2.0

I hava tried to installed in the following way:
  1. installing pytorch from source according the produce instroduced in the pytorch github
  2. setting "export CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0 $CFLAGS"" into ~/.bashrc
  3. installing the extension package (e.g., pytorch-scatter) from source code with command "python setup.py install"
   4. testing the installed package with commman "python setup.py test"
How, the error is appearing again!

I want to query whether the steps mentioned above is correct?
Thank for your help!

**Comment by rusty1s** [comment]
I'm a little helpless since the error message is so meaningless :( Did you try this in a fresh miniconda environment? There may be still version mismatches otherwise. So please:
1. Create a new miniconda environement
2. Install PyTorch via `conda install`
3. Clone the `torch-scatter` repo
4. Run `python setup.py install` and `python setup.py test`

**Comment by phaniram-sayapaneni** [comment]
This gave me this: #include <cstddef> , error: command 'gcc' failed with exit status 1
I have found some ulgy fix for this by using  CFLAGS='-stdlib=libc++’   pip install --verbose --no-cache-dir torch-cluster

works, but fails while importing torch_cluster
it throws:  Symbol not found: __ZN6caffe26detail36_typeMetaDataInstance_preallocated_0E
