### ISSUE TITLE
getDefaultCPUGenerator

### ISSUE THREAD

**Issue by sinanmut** [rusty1s/pytorch_cluster#27]
Hi,
 I am getting the following error when I try to install pytorch_cluster. My pytorch version is 1.1.0.
Any idea about how to fix it?
Thanks

cpu/sampler.cpp: In function ‘at::Tensor neighbor_sampler(at::Tensor, at::Tensor, size_t, float)’:
cpu/sampler.cpp:6:45: error: ‘getDefaultCPUGenerator’ is not a member of ‘at::detail’
    6 |   at::CPUGenerator *generator = at::detail::getDefaultCPUGenerator();
      |                                             ^~~~~~~~~~~~~~~~~~~~~~
cpu/sampler.cpp:27:32: error: ‘struct at::CPUGenerator’ has no member named ‘random’
   27 |         int64_t z = generator->random() % num_neighbors;

**Comment by sinanmut** [comment]
I installed it from pip repository instead of building it from source.

**Comment by rusty1s** [comment]
Yes, this should fix the issue. The change in master is only needed for PyTorch nightly.
