### ISSUE TITLE
classical K-Means clustering

### ISSUE THREAD

**Issue by qiulesun** [rusty1s/pytorch_cluster#31]
The classical K-Means clustering has been also widely used in many papers, including graph-based repreentation learning. Could you consider implementing it as a new feature?

**Comment by rusty1s** [comment]
Could you give me some pointers where k-means is used in combination with deep graph representation learning? Couldn't you simply use something like `scikit-learn` for this?

**Comment by qiulesun** [comment]
@rusty1s Does the script nearest.py directly implement the K-means clustering described in Section 3.3 (Initialization by Clustering) of NeurIPS2018 paper https://www.biostat.wisc.edu/~yli/preprints/yin_nips2018_camera_ready.pdf ?

**Comment by rusty1s** [comment]
The nearest method implements the batch-wise cluster assignment in the k-means algorithm. You need to then iteratively refine the cluster centers based on those assignments.
