### ISSUE TITLE
GPU version of Graclus may have deadlock?

### ISSUE THREAD

**Issue by jin-s13** [rusty1s/pytorch_cluster#35]
In some cases, the gpu-version Graclus may stuck... Maybe deadlock?
However, the cpu-version Graclus always works fine.

**Comment by rusty1s** [comment]
Do you have a minimal example to reproduce this?

**Comment by matherm** [comment]
I believe I found an answer to this...

In conrtrast to the cpu version, the cuda version of graclus uses internally a graph_coloring procedure (`colorize()` from coloring.cuh`).  Well, I'm not sure how this method is exactly implemented but I guess that it uses a random start configuration. 

In my case the handed graph was disconnected by mistake and so the colorize method could not terminate when its start configuration was bad.

The only real solution is checking for disconnected sub-graphs (e.g. doing a depth-search).

However, there are two  workarounds that might mitigate the issue:
1. Increasing the k-nearest neighbor search to avoid disconnected graphs.
2. Resetting a manual seed (`torch.manual_seed(10)`) for every pass through the network.

Does this help?

**Comment by rusty1s** [comment]
The GPU version of Graclus implements [this paper](http://www.staff.science.uu.nl/~bisse101/Articles/match12.pdf). I am not sure if setting a seed is the right choice to tackle this problem since you will generate equal coarsened graphs in every iteration. This may not generalize well to the test set.

**Comment by matherm** [comment]
That's right, I guess we should ensure connected graphs when using graclus.
