### ISSUE TITLE
Enhancement: radius

### ISSUE THREAD

**Issue by tchaton** [rusty1s/pytorch_cluster#39]
Hey @rusty1s,

Check this repo: https://github.com/humanpose1/torch_radius_neighbors/tree/master
Nanoflann is faster / robust than scipy on cpu and remove the need to convert back from numpy to torch. Integrating the code might be interesting here :)
Also, do you have any idea on how to improve the radius search which is currently built on brute force search (it won't scale to large pointcloud)

Best,
Thomas Chaton

**Comment by rusty1s** [comment]
Thank you for the pointer. As an alternative GPU computation, we should benchmark a KeOps implementation against the current approach

**Comment by tchaton** [comment]
This paper seems pretty interesting for the task

[semi_covex_hull_tree_icdm_accepted_final2.pdf](https://github.com/rusty1s/pytorch_cluster/files/3964385/semi_covex_hull_tree_icdm_accepted_final2.pdf)

**Comment by tchaton** [comment]
Hey @rusty1s,

This could be used to make radius search faster on gpu.
http://on-demand.gputechconf.com/gtc/2014/presentations/S4117-fast-fixed-radius-nearest-neighbor-gpu.pdf
