### ISSUE TITLE
Inconsistent number of neighbors being returned from knn_graph

### ISSUE THREAD

**Issue by SergioRAgostinho** [rusty1s/pytorch_cluster#40]
Version: 1.4.5

I'm getting an inconsistent number of nearest neighbours being returned from from `knn_graph` (cuda). I'll try to provide the actual data later. Currently I'm invoking the method as
```python
edge_index = knn_graph(P, k=5, batch=batch, loop=False)
```
`P` is of dim `[2048, 64]`, composed of a single batch
`batch` is a vector of zeros size 2048
The `flow` is set to its default value `source_to_target`.

`edge_index` is showing the following values
```python
# everything fine with this one. 5 neighbours per point
(Pdb) edge_index[1,:16]
tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3], device='cuda:0')
# at the end there are problems. indexes 2046 and 2047 are showing 6 times neighbours instead of 5
(Pdb) edge_index[1,-16:]
tensor([2045, 2045, 2045, 2045, 2046, 2046, 2046, 2046, 2046, 2046, 2047, 2047,
        2047, 2047, 2047, 2047], device='cuda:0')
```

**Comment by SergioRAgostinho** [comment]
[data.zip](https://github.com/rusty1s/pytorch_cluster/files/3972824/data.zip)

Extract the archive and load the data with `torch.load`. It's a dictionary object containing the contents of `P`, `batch` and `edge_index`.

**Comment by rusty1s** [comment]
Thank you! I will have a look.

**Comment by rusty1s** [comment]
Ok, I identified the issue. All entries in `P` are equal, so removing self-loops leads to an undefined behaviour since the loop may or may not be included in the initial `edge_index`. I am not really sure if this needs to be fixed since this is an untypical use-case for `knn_graph`.

**Comment by SergioRAgostinho** [comment]
> All entries in `P` are equal

Ok weird. If I'm interpreting what you wrote correctly, it means I missed a pretty naive mistake during debug. It wouldn't be the first time :man_shrugging:. I'll recheck things.
