### ISSUE TITLE
RuntimeError: expected scalar type Long but found Float

### ISSUE THREAD

**Issue by fabiopoiesi** [rusty1s/pytorch_cluster#41]
Hi,

I have this issue.

This is the code:
```
batch = torch.tensor(np.zeros(len(target)), dtype=torch.float)
target_tensor = torch.tensor(target, dtype=torch.float)
indices = fps(target_tensor, batch, ratio=0.5, random_start=False)
```

and this is the error:
RuntimeError: expected scalar type Long but found Float (data_ptr<long int> at /hardmnt/bumblebee1/data/fabio/research/DenseFusion/venv2/lib/python3.5/site-packages/torch/include/ATen/core/TensorMethods.h:5747)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f2282e1a813 in /home/poiesi/data/research/DenseFusion/venv2/lib/python3.5/site-packages/torch/lib/libc10.so)
frame #1: long* at::Tensor::data_ptr<long>() const + 0x16c (0x7f22106fdb8c in /home/poiesi/data/research/DenseFusion/venv2/lib/python3.5/site-packages/torch_cluster/fps_cpu.cpython-35m-x86_64-linux-gnu.so)
frame #2: fps(at::Tensor, at::Tensor, float, bool) + 0x76 (0x7f22106fa116 in /home/poiesi/data/research/DenseFusion/venv2/lib/python3.5/site-packages/torch_cluster/fps_cpu.cpython-35m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x22df4 (0x7f221070fdf4 in /home/poiesi/data/research/DenseFusion/venv2/lib/python3.5/site-packages/torch_cluster/fps_cpu.cpython-35m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x2302e (0x7f221071002e in /home/poiesi/data/research/DenseFusion/venv2/lib/python3.5/site-packages/torch_cluster/fps_cpu.cpython-35m-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x1f656 (0x7f221070c656 in /home/poiesi/data/research/DenseFusion/venv2/lib/python3.5/site-packages/torch_cluster/fps_cpu.cpython-35m-x86_64-linux-gnu.so)
frame #6: PyCFunction_Call + 0x77 (0x4e1307 in /home/poiesi/data/research/DenseFusion/venv2/bin/python)
...

Any guess?
Thanks

**Comment by rusty1s** [comment]
`batch` needs to be a `long` tensor.
