### ISSUE TITLE
installation gcc errors

### ISSUE THREAD

**Issue by kjhenner** [rusty1s/pytorch_cluster#52]
I'm getting some GCC errors when I try to install. The full output is [here](https://gist.github.com/kjhenner/7a2f18d3a2be799634950ab87ec33792). I have the PATH and CPATH environment variables set per the README installation instructions. I'm installing in a conda environment, which I suspect may be complicating things, but I'm at a bit of a loss as to how to proceed resolving the issue. I'd be grateful for any suggestions and glad to provide any additional details.

**Comment by rusty1s** [comment]
This is strange. Which PyTorch version are you using?

**Comment by kjhenner** [comment]
The pytorch version is 1.3.0a0+bb4f380

I noticed that those errors are all occurring in the environment of `DATA_PTR`, which is conditionally defined on the `VERSION_GE_1_3` flag. If I comment out the logic for that in the `setup.py` so it doesn't pass that flag, it will install, but with the following errors:
```
/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00001d27_00000000-7_graclus_kernel.cpp1.ii".
```

If I try to import any module, I get: `ModuleNotFoundError: No module named 'torch_cluster.graclus_cpu'`

If I comment out everything but sample_neighbors from the `__init__.py`, I can actually import that. It's all I need from pytorch-cluster, so I was hoping perhaps I could settle with that, but unfortunately I also get similar errors for dependencies in pytorch-sparse.

**Comment by kjhenner** [comment]
It looks like my version of PyTorch didn't have the data/data_ptr change. It seems like that should be in any version >= 1.3, so I'm not sure what was going on.

I'm stuck with cuda 9.1, though, and can't figure out if there's a way to get torch-scatter working with that, but I suppose that's a separate problem!

I'll leave the issue open for now in case you want to look into whether that PyTorch version check isn't sufficient to determine how to handle that DATA_PTR macro, but if not, feel free to close the issue.

**Comment by rusty1s** [comment]
You can check out the `torch-scatter<2.0` release, modify the `DATA_PTR` macro and install it by running `python setup.py install`. This should work fine.

**Comment by kjhenner** [comment]
Thanks for this suggestion--I've been busy working on another project for the last few days, but I will give this a try as soon as I'm able!

**Comment by kjhenner** [comment]
Thanks--I was able to get this working torch-scatter<2.0 and a corresponding version of torch-sparse--0.4.3, I think.
