### ISSUE TITLE
What does the output of `grid_cluster` represent?

### ISSUE THREAD

**Issue by SergioRAgostinho** [rusty1s/pytorch_cluster#53]
Hey Matthias,

I'm trying to get some additional insight into what the `grid_cluster` function outputs. The readme links to a reference paper in which the authors mention they used a voxel grid filter from PCL. That filter generates a filtered copy of the input data.  On the other hand, `grid_cluster` appears to be output indices but it there's no way of knowing the voxel centers used for clustering.

At some point I also considered that these might be indexes from the original input data, but the example in the readme contradicts that.
```python
import torch
from torch_cluster import grid_cluster

pos = torch.Tensor([[0, 0], [11, 9], [2, 8], [2, 2], [8, 3]])
size = torch.Tensor([5, 5])

cluster = grid_cluster(pos, size)
```
```
>>> print(cluster)
tensor([0, 5, 3, 0, 1])
```
Index 5 is too large for an input of size 5.

So my question is, what does the output of `grid_cluster` represent?

**Comment by rusty1s** [comment]
It assigns each point to a cluster index. Points with the same index belong to the same cluster. If you want your indices to be contiguous (starting from zero), you can use the function `consecutive_cluster` afterwards.

**Comment by SergioRAgostinho** [comment]
OK thanks.

**Comment by Sentient07** [comment]
Hello @rusty1s , I find that `grid_cluster` returns a fortran indexing while I'd like a 'C' indexing. Currently, `grid_cluster` is equivalent of `np.ravel_multi_index(..., order='F')` but I'd like `np.ravel_muti_index(..., order='C')`. I couldn't find the `consecutive_cluster` function. Can you please help me out? Thanks
