### ISSUE TITLE
unable to execute '/usr/local/cuda:/bin/nvcc': No such file or directory

### ISSUE THREAD

**Issue by MHS-Gautam** [rusty1s/pytorch_cluster#55]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -shared -B /home/gautam/anaconda3/compiler_compat -L/home/gautam/anaconda3/lib -Wl,-rpath=/home/gautam/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/cpu/sampler.o -o build/lib.linux-x86_64-3.7/torch_cluster/sampler_cpu.cpython-37m-x86_64-linux-gnu.so
building 'torch_cluster.graclus_cuda' extension
creating build/temp.linux-x86_64-3.7/cuda
gcc -pthread -B /home/gautam/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gautam/anaconda3/lib/python3.7/site-packages/torch/include -I/home/gautam/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/gautam/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/gautam/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda:/include -I/home/gautam/anaconda3/include/python3.7m -c cuda/graclus.cpp -o build/temp.linux-x86_64-3.7/cuda/graclus.o -DVERSION_GE_1_3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=graclus_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda:/bin/nvcc -I/home/gautam/anaconda3/lib/python3.7/site-packages/torch/include -I/home/gautam/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/gautam/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/gautam/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda:/include -I/home/gautam/anaconda3/include/python3.7m -c cuda/graclus_kernel.cu -o build/temp.linux-x86_64-3.7/cuda/graclus_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DVERSION_GE_1_3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=graclus_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++11
unable to execute '/usr/local/cuda:/bin/nvcc': No such file or directory
error: command '/usr/local/cuda:/bin/nvcc' failed with exit status 1

System Details:
Python 3.7
CUDA 10.0
NVCC working

I think it's the colon in the address that's messing my installation?

**Comment by rusty1s** [comment]
Yes, this seems to be a bug in your `$PATH` variable.

**Comment by MHS-Gautam** [comment]
I don't see an issue with my path variable. here's how my path variable looks "/usr/local/cuda/bin:/home/gautam/anaconda3/bin:/home/gautam/anaconda3/condabin:/home/gautam/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

**Comment by MHS-Gautam** [comment]
Yeah, you're right. There's an issue with my CUDA_HOME variable. Thanks!!!
