### ISSUE TITLE
How to make sure it runs on cuda

### ISSUE THREAD

**Issue by aniqueakhtar** [rusty1s/pytorch_cluster#56]
I am using an anaconda environment.

These do not hold true for me:
```
$ echo $PATH
>>> /usr/local/cuda/bin:...

$ echo $CPATH
>>> /usr/local/cuda/include:...
```

I believe the current code is not working on GPU. How can I make sure I can run it on the GPU?

Also, I installed using pip so I can't run this command either:
`python setup.py test
`

Thanks

**Comment by rusty1s** [comment]
I am not sure I understand? Did you run `pip install ...`? What is the error message?
