### ISSUE TITLE
Does it support win10

### ISSUE THREAD

**Issue by 45825529** [rusty1s/pytorch_cluster#58]
![image](https://user-images.githubusercontent.com/8955168/76677483-c68ba200-6609-11ea-9a70-f0d983cb9584.png)

**Comment by rusty1s** [comment]
Yes, but it is way easier to install if you simple use the provided binaries :)

**Comment by liaopeiyuan** [comment]
@45825529 could you please provide the entire error message? It's kinda hard to tell from the current one.
请问您能提供完整的错误信息吗？理论上来说win10是可以编译的。
