### ISSUE TITLE
Latest binaries not found in link

### ISSUE THREAD

**Issue by alantrrs** [rusty1s/pytorch_cluster#60]
Looks like the site doesn't have a [link](https://pytorch-geometric.com/whl/torch-1.4.0.html) for the `torch_cluster` binaries. So the following instruction from the REAME is failing:
```
pip install torch-cluster==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.4.0.html
```

**Comment by rusty1s** [comment]
Fixed!
