### ISSUE TITLE
The results of graclus_cluster

### ISSUE THREAD

**Issue by bwdeng20** [rusty1s/pytorch_cluster#64]
I've tested graclus_cluster  on random graphs(density=0.2)  with size varing from 10 ~ 4000. In all cases, graclus_cluster obtains many tiny clusters which usually have only 2 nodes. I am not sure if this phenomenon is normal.  The figure below demonstrates what I said.
![newplot (6)](https://user-images.githubusercontent.com/26434203/78877549-9a860400-7a83-11ea-88d9-34675ed61bad.png)

**Comment by rusty1s** [comment]
Yes, `graclus_cluster` works by grouping two connected nodes, so the number of nodes per cluster is 2 at maximum. If you want bigger clusters, you can iteratively apply `graclus_cluster`.

**Comment by bwdeng20** [comment]
Could you please give me a multi-level `graclus_cluster`  example to throw light on the details of it?

**Comment by rusty1s** [comment]
You can find an example [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/mnist_graclus.py#L38-L40), where you can repeatedly call `graclus_cluster` and `max_pool` to obtain coarser graphs. This is the procedure describes in [this paper](https://arxiv.org/abs/1606.09375).

**Comment by bwdeng20** [comment]
Thx
