### ISSUE TITLE
graclus result in readme

### ISSUE THREAD

**Issue by shawnthu** [rusty1s/pytorch_cluster#65]
import torch
from torch_cluster import graclus_cluster

row = torch.tensor([0, 1, 1, 2])
col = torch.tensor([1, 0, 2, 1])
weight = torch.Tensor([1, 1, 1, 1])  # Optional edge weights.

cluster = graclus_cluster(row, col, weight)
print(cluster)
tensor([0, 0, 1])

The result seems to be 'tensor([0, 0, 2])' in my mac

**Comment by rusty1s** [comment]
I do not think this is a big problem since `graclus_cluster` outputs are likely to vary because of the randomness of the algorithm.

**Comment by bwdeng20** [comment]
You can test `graclus` on more graphs with larger sizes. The results of my experiments show that given `C` clusters, the cluster ordinals, e.g., `2` and `0` in your returned tensor,  are not restricted to a permutation of `range(C)`. If you prefer that , this may help you.
``` python3
assign= graclus_cluster(row, col, weight)
_, assign=assign.unique(return_inverse=True)
```
