### ISSUE TITLE
[BUG] INTERNAL ASSERT FAILED when performing fps

### ISSUE THREAD

**Issue by Na-Z** [rusty1s/pytorch_cluster#67]
Hi rusty,

When applying fps, sometimes I came across the following bug:
```
   fps_index = fps(feat, None, ratio=ratio, random_start=False)
RuntimeError: ratio > 0 && ratio < 1 INTERNAL ASSERT FAILED at /home/travis/build/rusty1s/pytorch_cluster/csrc/cuda/fps_cuda.cu:73, please report a bug to PyTorch. Invalid input
The above operation failed in interpreter.
Traceback (most recent call last):
  File "/home/anaconda3/envs/env_fsseg/lib/python3.6/site-packages/torch_cluster/fps.py", line 48
        ptr = torch.tensor([0, src.size(0)], device=src.device)
```

Do you have any idea why this happens?

**Comment by rusty1s** [comment]
It says that `ratio` should be in `(0,1)`. With which value do you call it?

**Comment by Na-Z** [comment]
> It says that `ratio` should be in `(0,1)`. With which value do you call it?
Oh I think I know the problem.

In my case,  the ratio is dynamically computed. Maybe in some extreme cases, the ratio is larger than 1. 

Thanks. I will make a further check.
