### ISSUE TITLE
What about writing some C++ examples?

### ISSUE THREAD

**Issue by WMF1997** [rusty1s/pytorch_cluster#70]
Hello @rusty1s , 
I found that the C++ library you mentioned does not have an example, so I wrote one example. I just translate the graclus example in python to C++. 

Here is my example in CLion Project. And the PyTorch and Libtorch are both 1.6.0a0 built from source. 

main.cpp

```cpp
// main.cpp
#include <iostream>
#include <vector>
#include <torch/torch.h>
#include <torchcluster/cluster.h>  // newly added here.
#include <Python.h>  // I do not know why <Python.h> should be set here? But, ... it only works with Python.h is included, I use anaconda
using namespace std;
int main (int argc, const char* argv[]) {
    vector<int> row_1 = {0, 1, 1, 2};
    vector<int> col_1 = {1, 0, 2, 1};
    vector<float> weight_1 = {1, 1, 1, 1};
    torch::Tensor row = torch::tensor(row_1);
    torch::Tensor col = torch::tensor(col_1);
    torch::Tensor weight = torch::tensor(weight_1);
    torch::Tensor res = graclus(row, col, weight);
    cout << res << endl;
    return 0;
}  // main
```
CMakeLists.txt

```txt
# CMakeLists.txt
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(untitiled)

set(CMAKE_PREFIX_PATH "/home/wmf997/pytorch/torch")
find_package(Torch REQUIRED)

include_directories("/home/wmf997/anaconda3/envs/pytorch_src/include/python3.6m/")  # my anaconda include path

add_executable(main main.cpp)

target_link_libraries(main "${TORCH_LIBRARIES}")
target_link_libraries(main "/home/wmf997/pytorch/torch/lib/libtorchcluster.so")  # my path

set_property(TARGET main PROPERTY CXX_STANDARD 14)
```

The result:
![Screenshot_20200522_183913](https://user-images.githubusercontent.com/37621591/82659676-a4428000-9c5b-11ea-9ef6-66f776b87822.png)

This is the final result in cpp. 

P.S. I find that ```torch_cluster```, ```torch_scatter```, ```torch_sparse```, ```torch_spline_conv``` have all provided C++ library, but the detailed example is not provided here, the documentation about using C++ frontend in pyg ecosystem is not well-provided. 
Take the example of graclus above as an example, the python example can be just written as below in your example

```python
import torch
from torch_cluster import graclus_cluster

row = torch.tensor([0, 1, 1, 2])
col = torch.tensor([1, 0, 2, 1])
weight = torch.Tensor([1, 1, 1, 1])  # Optional edge weights.

cluster = graclus_cluster(row, col, weight)
```

Code Writing is very easy. However, this kinds of easy hides something which is very important in C++. The type of ```row``` and ```col``` should be an integer (`torch::kInt64`), while `weight` should be (`torch::kFloat32` or `torch::kFloat64`). So I suggest that the example code in Python can consider this, and I think weight in Python can be written as:
```python
weight = torch.Tensor([1.,1.,1.,1.])
```

or 

```python
weight = torch.Tensor([1,1,1,1], dtype=torch.float32)
```

yours sincerely, 
@wmf1997

**Comment by rusty1s** [comment]
Thanks, I modified the `README` examples accordingly. I think your example is great! Do you mind sending a PR?
