### ISSUE TITLE
neighbor_sampler description

### ISSUE THREAD

**Issue by kkonevets** [rusty1s/pytorch_cluster#71]
Hi! 
Can you please give a mathematical formula of `neighbor_sampler()` function? 
I see that it takes node ids, cumulative degree and sample size, but what it does exactly and why it works? A link with description would be sufficient. 
Thx

**Comment by kkonevets** [comment]
O, I got it!
For example, if we have sorted node list like this:
1 1 2 2 2 2 2 2 3 4 4 4 4 4 4 4
this gives cumulative degree  
0 2 6 9 16
and if node ids [2, 3] and sample size is 3, 
then we sample 3 indices from each group (nodes 3 and 4 in this case):
8 11 14 15
or
8 13 9 14
and so on...

**Comment by rusty1s** [comment]
Yes, exactly :)

**Comment by rusty1s** [comment]
I agree though that documentation is kinda lackluster, I will try to improve it.

**Comment by kkonevets** [comment]
in spite of that you made a good job, thanks
