### ISSUE TITLE
max_num_neighbors in radius function

### ISSUE THREAD

**Issue by dhorka** [rusty1s/pytorch_cluster#72]
Hi,

I would like to ask a doubt that I have in radius function related to the max_num_neighbors parameter. When you specify this parameter, are the points returned by the function the closest to the point x? I mean, imagine that with the specified radius, you have 1000 possible nearest points, and you have defined the max_num_neighbors=32. Will the function return the 32 values closest to the centroid?

I was trying to figure out the behavior of this on the code, but I'm not able to find the documentation of this function: 
https://github.com/rusty1s/pytorch_cluster/blob/32fa3257801a22862c515031b4c35318af51d2f5/torch_cluster/radius.py#L75

**Comment by yanconglin** [comment]
had the same doubt. If I understand correctly, the source files are there (depends on cuda or cpu): https://github.com/rusty1s/pytorch_cluster/tree/master/csrc

**Comment by rusty1s** [comment]
Sorry, I missed that issue. In general, the radius function will not return the closest point in case `num_nearest_points > max_num_neighbors`. That's a current limitation of our GPU kernel.

**Comment by nlgranger** [comment]
In case `num_nearest_points` > `max_num_neighbors`, is there a pattern in the selected neighbors on GPU? For example, if I shuffle points before calling the function is it going to uniformly take `max_num_neighbors` among the neighbors?

**Comment by rusty1s** [comment]
There is no pattern in selecting the neighbors since GPU threads may process nodes in any order.

**Comment by jaredsagendorf** [comment]
Same question led me here. It would actually be nice if there was a way to control this - perhaps an option that would either rank the neighbours by distance and return the `max_num_neighbors` nearest, or farthest or to ensure the neighbours are uniformly sampled. 

I know turning on those options would decrease performance, but that might be worth it for some applications.
