### ISSUE TITLE
Memory leak in knn_graph (cpu) in version 1.5.5

### ISSUE THREAD

**Issue by SergioRAgostinho** [rusty1s/pytorch_cluster#75]
There appears to a memory leak in the cpu version of `knn_graph` of version 1.5.5. The changelog reports a new cpu version of nn search so I assume it's still undergoing maturity. 

```python
import torch
from torch_cluster import knn_graph

data = torch.load("data.pth")
while True:
    knn_graph(data["pointcloud"], k=data["k"], batch=data["batch"], loop=False)
```
Extract the data package from the zip file.
[data.pth.zip](https://github.com/rusty1s/pytorch_cluster/files/4907704/data.pth.zip)

**Comment by rusty1s** [comment]
Thanks for reporting. @liaopeiyuan, can you take a look?

**Comment by liaopeiyuan** [comment]
Got it!

**Comment by SergioRAgostinho** [comment]
I haven't validated anything but from looking at the source code there's a couple of things which look suspicious
https://github.com/rusty1s/pytorch_cluster/blob/c8e167a77bd10c1d8698a2205013160ceebaf6ce/csrc/cpu/knn_cpu.cpp#L25

Here you create  vector on the heap, which itself allocates the actual memory to hold data. This vector object is never deleted in this scope. 

https://github.com/rusty1s/pytorch_cluster/blob/c8e167a77bd10c1d8698a2205013160ceebaf6ce/csrc/cpu/knn_cpu.cpp#L51-L53

Here you create a tensor from data. Does `tensor::from_blob` take ownership of the data provided in this pointer?
  - If yes, you should not pass the data pointer of a `std::vector` to it. You should just allocate raw memory with `new` and pass it to the method
  - If no, you're still leaking all the control variables that `std::vector` uses internally.

**Comment by rusty1s** [comment]
You're absolutely right. I reverted back the changes we made and fixed the memory leak in `knn_cpu.pp` and `radius_cpu.cpp` stemming from `new std::vector`. However, `nanoflann_neighbors` still allocates a lot of memory that never gets released.

@liaopeiyuan Please let me know if you have time to fix this.

**Comment by liaopeiyuan** [comment]
Sorry, I wasn't aware that `nanoflann_neighbors` had memory leaking issues. I'm very new to C++ development and I was mainly writing code in C, so pardon me for the rookie mistakes. I'm pretty occupied for the following two weeks but after that I'll have more time. I will fix all heap allocations in the upcoming weeks (should be easy since the core code isn't too long), and see if I can modify the internals of nanoflann.

**Comment by rusty1s** [comment]
No worries. Since this is kinda urgent, I will try to fix it on the weekend. Will let you know how it goes.

**Comment by rusty1s** [comment]
Fixed in https://github.com/rusty1s/pytorch_cluster/pull/77. I have removed threading support for the sake of simplicity, and will add it back in a later PR.
