### ISSUE TITLE
Same indices exists in the result of torch_cluster.Fps function, is it a bug

### ISSUE THREAD

**Issue by MichaleWong** [rusty1s/pytorch_cluster#80]
There're several same point indices existing in the result of Fps function, I think that should be unique tensor,  is it a bug?

my code situation:
my fps_idx.shape:torch.Size([65536])
after torch.unique(fps_idx), the shape is torch.Size([63937])

**Comment by rusty1s** [comment]
I cannot really seem to reproduce this. Do you have a minimal example to reproduce?
