### ISSUE TITLE
how to deal with weights of nodes in Graclus?

### ISSUE THREAD

**Issue by mujm** [rusty1s/pytorch_cluster#86]
Hello, I find that weights of vertices are used in Coarsening Phase in https://www.cs.utexas.edu/users/inderjit/public_papers/multilevel_pami.pdf(url).

However, there is only one optional parameter for weights of edges in graclus.py. Then how to deal with weights of nodes?
Thanks!

**Comment by rusty1s** [comment]
That is something that is currently not implemented, sorry!

**Comment by mujm** [comment]
> That is something that is currently not implemented, sorry!

Thanks for your reply!!
