### ISSUE TITLE
Random_walk p, q parameters

### ISSUE THREAD

**Issue by cjissmart** [rusty1s/pytorch_cluster#87]
I found that the p, q parameters of torch_cluster.random_walk are fixed as 1 a few months ago. And an important model, Node2vec, is based on torch_cluster.random_walk. The p, q parameters of Node2vec which can significantly affect the performance of the model is the same as torch_cluster.random_walk. I hope it could be solved as quickly as possible.

![image](https://user-images.githubusercontent.com/37531166/95088425-7c3b5100-0712-11eb-90f6-14d08381cc77.png)

**Comment by rusty1s** [comment]
This is on the [roadmap](https://github.com/rusty1s/pytorch_geometric/issues/1465).

**Comment by cjissmart** [comment]
> This is on the [roadmap](https://github.com/rusty1s/pytorch_geometric/issues/1465).

Thanks~ I'll update my version.

**Comment by rusty1s** [comment]
This is now included in torch-cluster==master and will be pushed to an official release soon.
