### ISSUE TITLE
Customizing the KNN nearest method

### ISSUE THREAD

**Issue by tyua321** [rusty1s/pytorch_cluster#89]
Hi Matthias,

I noticed that  `DynamicEdgeConv` can updated the edge with the KNN Euclidean distance, I want to customize the distance function, for example using some sort of dynamic time warping method to compute the distance. I checked `knn.py` but still not quite understood it. Can you give me some help on change the distance function?

Sorry for the trivia question, I am new to Pytorch and graph neural network.

**Comment by rusty1s** [comment]
You can customize the distance function directly in the CUDA kernel code, see [here](https://github.com/rusty1s/pytorch_cluster/blob/master/csrc/cuda/knn_cuda.cu#L60-L63).

**Comment by Shudeng** [comment]
Hello, @rusty1s 
Thanks for your wonderful work. Can you consider knn with a specific radius like that in sklearn?
``` python
from sklearn.neighbors import NearestNeighbors
neigh = NearestNeighbors(n_neighbors=2, radius=0.4)
```

**Comment by rusty1s** [comment]
How about using `knn` just as normal, and filtering out all points with radius greather than `radius` afterwards?
```python
edge_index = knn_graph(x, k=2, batch=batch)
row, col = edge_index
dist = (x[row] - x[col]).norm(dim=-1)
mask = dist <= radius
edge_index = edge_index[:, mask]
```
Alternatively, you can use `radius_graph` with `max_num_neighbors`, but this is not guaranteed to return the closest points on GPU.
