### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_cluster.knn_cuda'

### ISSUE THREAD

**Issue by abahnasy** [rusty1s/pytorch_cluster#93]
I'm facing this error while trying to import torch_cluster.knn_cuda, I've followed the installation guide and everything went smoothly without any errors

My env variables
`echo $PATH 
../usr/local/cuda/bin..`

`echo $CPATH
/usr/local/cuda/include`

could you please advise about solving this problem?

**Comment by rusty1s** [comment]
There is no file named `knn_cuda`. Instead, you can import the `knn` function which works for both CPU and CUDA: `from torch_cluster import knn`.

**Comment by abahnasy** [comment]
Oh, I was trying to run the code mentioned here 
https://pytorch-geometric.readthedocs.io/en/1.3.0/_modules/torch_cluster/knn.html

'torch_cluster import knn' works fine

Thank you
