### ISSUE TITLE
CPU version runs faster than GPU version

### ISSUE THREAD

**Issue by Kaipiranha** [rusty1s/pytorch_cluster#99]
Hey guys,

I did several tests utilizing different torch_cluster functions and found that for a lot of implementations like knn, knn_graph, radius and radius_graph the CPU version for me runs (way) faster than the GPU one. In my tests I was using point clouds with approximately 100k points and e.g. using knn with 20 nearest neighbours on CPU takes 0.4 seconds with the GPU version taking a total of 145 seconds. Other functions like nearest work faster on GPU (0.00020 seconds) than CPU (51 seconds).

It is really strange! Is anyone else experiencing this kind of issues? Maybe there was also something wrong with my installation. I am using pytorch 1.8.0 and installed torch_cluster via pip.

Thanks a lot.

**Comment by rusty1s** [comment]
Yeah, the CUDA implementation will be really slow when operating on huge point clouds. Our current implementation parallelizes across the batch dimension. I will look into more efficient CUDA `knn` implementations.

**Comment by Kaipiranha** [comment]
Thank you for your answer, so I can stop searching for the error in my installation process.

I think adapting the CUDA implementation in this way would be pretty essential then to ensure a decent GPU support. Please keep me updated on the progress!

**Comment by legel** [comment]
It would be amazing if someone could develop a KDTree implementation for CUDA. I stumbled across the CPU's implementation through Google, searching for a KDTree implementation in PyTorch, i.e. `KDTreeVectorOfVectorsAdaptor`.  As-is, this is project is the closest thing available, but I'm sure a CUDA implementation of the KDTree for PyTorch3D could really take advantage of the parallelization, potentially be 10-100x faster than anything out there...

**Comment by BarakeelFanseuKamhoua** [comment]
Hello, Thank you guys for the great work. Please is there any updates on parallel KNN search with torch_gpu for massive point clouds? That parallelizes across vertices as well as batches and as such is faster than cpu?

God bless.
